version: '3.0'

services:
    redis-db:
        image: redis
    backend:
        image: hello-backend
        ports:
            - 5000:8080
        environment:
            - REDIS_HOST=redis-db
        restart: unless-stopped

    frontend:
        image: hello-frontend
        ports:
            - 3000:5000