version: '3.0'

services:
    nginx:
        image: nginx:alpine
        volumes: 
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80

    redis-db:
        image: redis:alpine

    pestgres-db:
        image: postgres:alpine
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=example
            
    backend:
        image: hello-backend:scratch
        build: ./example-backend/
        environment:
            - REDIS_HOST=redis-db
            - POSTGRES_HOST=pestgres-db
            - POSTGRES_PASSWORD=example
        restart: unless-stopped

    frontend:
        image: hello-frontend:nginx-alpine
        build: ./example-frontend/