version: "3"
services:
  image-builder:
    image: romanmvasilyev/image-builder
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: image-builder
    command: https://github.com/docker-hy/ml-kurkkumopo-backend.git ml-backend
