# Exercise 1.11 is taken as the base case.
# We need Java 8. I found this from docker hub.
FROM openjdk:8 AS build-phase

EXPOSE 8080

# It is a previous excercise with Java Spring backend - Ex
WORKDIR /usr/src/app

# Copy all of the content from the project to the image
COPY . .

# README: Build the project with
RUN ./mvnw package

# README: Run with
CMD ["java", "-jar", "./target/docker-example-1.1.3.jar"]