FROM node:14-alpine3.13

EXPOSE 5000

WORKDIR /usr/src/app

# Copy all of the content from the project to the image.
COPY . .

# serve package will serve the app.
RUN npm install -g serve && \
# Install project packages.
    npm install && \
# Deploy
    npm run build && \
    ls | grep -v build | xargs rm -rf && \
# Add a non-root user
    adduser -D appuser

USER appuser

ENTRYPOINT [ "serve", "-s", "-l", "5000", "build" ]